// <auto-generated />

import basicSsl from '@vitejs/plugin-basic-ssl';
import react from '@vitejs/plugin-react';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import process from 'node:process';
import { defineConfig, loadEnv } from 'vite';

const __dirname = import.meta.dirname;

const ikonEmbedHeaders = {
  name: 'ikon-embed-headers',
  configureServer(server) {
    server.middlewares.use((_req, res, next) => {
      res.setHeader('Cross-Origin-Embedder-Policy', 'credentialless');
      res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');
      next();
    });
  },
};

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), 'VITE_');

  const port = Number(process.env.VITE_SERVER_PORT || env.VITE_SERVER_PORT || 9443);
  const frontendHost = process.env.VITE_SERVER_FRONTEND_HOST || env.VITE_SERVER_FRONTEND_HOST || 'localhost';
  const frontendPort = Number(process.env.VITE_SERVER_FRONTEND_PORT || env.VITE_SERVER_FRONTEND_PORT || port);
  const frontendUrl = process.env.VITE_SERVER_FRONTEND_URL || env.VITE_SERVER_FRONTEND_URL || `https://${frontendHost}:${frontendPort}`;
  const openBrowser = (process.env.VITE_SERVER_OPEN_BROWSER || env.VITE_SERVER_OPEN_BROWSER) === 'true';
  const isTunneled = (process.env.VITE_SERVER_TUNNELED || env.VITE_SERVER_TUNNELED) === 'true';
  const authRequireSignIn = (process.env.VITE_IKON_AUTH_REQUIRE_SIGN_IN || env.VITE_IKON_AUTH_REQUIRE_SIGN_IN) === 'true';
  const authMethods = process.env.VITE_IKON_AUTH_METHODS || env.VITE_IKON_AUTH_METHODS ? JSON.parse(process.env.VITE_IKON_AUTH_METHODS || env.VITE_IKON_AUTH_METHODS) : ['google'];
  const authSpaceId = process.env.VITE_IKON_AUTH_SPACE_ID ?? env.VITE_IKON_AUTH_SPACE_ID ?? '';
  const backendUrl = process.env.VITE_IKON_BACKEND_URL || env.VITE_IKON_BACKEND_URL || '';
  const authUrl = process.env.VITE_IKON_AUTH_URL || env.VITE_IKON_AUTH_URL || '';
  const devLoginToken = process.env.VITE_IKON_DEV_LOGIN_TOKEN || env.VITE_IKON_DEV_LOGIN_TOKEN || '';
  const devLoginRunId = process.env.VITE_IKON_DEV_LOGIN_RUN_ID || env.VITE_IKON_DEV_LOGIN_RUN_ID || '';
  const waitForExternalConnectUrl = (process.env.VITE_WAIT_FOR_EXTERNAL_CONNECT_URL || env.VITE_WAIT_FOR_EXTERNAL_CONNECT_URL) === 'true';
  const localIkonServerEnabled = (process.env.VITE_LOCAL_IKON_SERVER_ENABLED || env.VITE_LOCAL_IKON_SERVER_ENABLED) === 'true';
  const localIkonServerHost = process.env.VITE_LOCAL_IKON_SERVER_HOST || env.VITE_LOCAL_IKON_SERVER_HOST || 'localhost';
  const localIkonServerPort = Number(process.env.VITE_LOCAL_IKON_SERVER_PORT || env.VITE_LOCAL_IKON_SERVER_PORT || '8443');
  const certPath = (process.env.VITE_IKON_SERVER_CERT_PATH || env.VITE_IKON_SERVER_CERT_PATH)?.trim();
  const keyPath = (process.env.VITE_IKON_SERVER_KEY_PATH || env.VITE_IKON_SERVER_KEY_PATH)?.trim();
  const hasCertificate = !isTunneled && certPath && keyPath && existsSync(certPath) && existsSync(keyPath);
  const isIkonInternal = (process.env.VITE_IS_IKON_INTERNAL || env.VITE_IS_IKON_INTERNAL) === 'true';
  const platformTypescriptPath = process.env.VITE_IKON_PLATFORM_TYPESCRIPT_PATH || env.VITE_IKON_PLATFORM_TYPESCRIPT_PATH;

  const plugins = [ikonEmbedHeaders, react()];

  if (!hasCertificate && !isTunneled) {
    plugins.push(basicSsl());
  }

  const httpsConfig = isTunneled ? false : hasCertificate ? { cert: readFileSync(certPath), key: readFileSync(keyPath) } : true;
  const resolveConfig = {};

  if (isIkonInternal && platformTypescriptPath) {
    resolveConfig.alias = {
      '@ikonai/sdk-react-ui/fonts': resolve(platformTypescriptPath, 'sdk/sdk-react-ui/fonts'),
      '@ikonai/sdk-react-ui/theme': resolve(platformTypescriptPath, 'sdk/sdk-react-ui/theme'),
      '@ikonai/sdk': resolve(platformTypescriptPath, 'sdk/sdk/src/index.ts'),
      '@ikonai/sdk-libopus': resolve(platformTypescriptPath, 'sdk/sdk-libopus/src/index.ts'),
      '@ikonai/sdk-react-ui': resolve(platformTypescriptPath, 'sdk/sdk-react-ui/src/index.ts'),
      '@ikonai/sdk-react-ui-standard': resolve(platformTypescriptPath, 'sdk/sdk-react-ui-standard/src/index.ts'),
      '@ikonai/sdk-ui': resolve(platformTypescriptPath, 'sdk/sdk-ui/src/index.ts'),
      '@ikonai/configs': resolve(platformTypescriptPath, 'shared/configs/src/index.ts'),
      '@ikonai/protocol': resolve(platformTypescriptPath, 'shared/protocol/src/index.ts'),
      react: resolve(__dirname, 'node_modules/react'),
      'react-dom': resolve(__dirname, 'node_modules/react-dom'),
    };
  }

  const fsAllow = [__dirname];

  if (isIkonInternal && platformTypescriptPath) {
    fsAllow.push(platformTypescriptPath);
  }

  const optimizeDepsConfig = {
    include: ['react', 'react-dom'],
    entries: ['src/main.tsx'],
    rolldownOptions: { transform: { target: 'es2019' } },
  };

  if (!isIkonInternal) {
    optimizeDepsConfig.exclude = ['@ikonai/sdk', '@ikonai/sdk-ui'];
  }

  return {
    cacheDir: 'node_modules/.ikon-vite-cache',
    // The app folder contract: static web files live in the app root's public/, one level above
    // frontend-node. An app not yet migrated keeps Vite's local default.
    publicDir: existsSync(resolve(__dirname, '../public')) ? resolve(__dirname, '../public') : 'public',
    plugins,
    resolve: resolveConfig,
    worker: {
      format: 'es',
    },
    define: {
      __IKON_AUTH_REQUIRE_SIGN_IN__: JSON.stringify(authRequireSignIn),
      __IKON_AUTH_METHODS__: JSON.stringify(authMethods),
      __IKON_AUTH_SPACE_ID__: JSON.stringify(authSpaceId),
      __IKON_BACKEND_URL__: JSON.stringify(backendUrl),
      __IKON_AUTH_URL__: JSON.stringify(authUrl),
      __IKON_DEV_LOGIN_TOKEN__: JSON.stringify(devLoginToken),
      __IKON_DEV_LOGIN_RUN_ID__: JSON.stringify(devLoginRunId),
      __IKON_WAIT_FOR_EXTERNAL_CONNECT_URL__: JSON.stringify(waitForExternalConnectUrl),
      __IKON_LOCAL_IKON_SERVER_ENABLED__: JSON.stringify(localIkonServerEnabled),
      __IKON_LOCAL_IKON_SERVER_HOST__: JSON.stringify(localIkonServerHost),
      __IKON_LOCAL_IKON_SERVER_PORT__: JSON.stringify(localIkonServerPort),
    },
    optimizeDeps: optimizeDepsConfig,
    server: {
      open: openBrowser ? frontendUrl : false,
      host: '0.0.0.0',
      port: port,
      https: httpsConfig,
      strictPort: true,
      fs: {
        allow: fsAllow,
      },
      hmr: {
        host: frontendHost,
        clientPort: frontendPort,
        protocol: 'wss',
      },
      watch: {
        usePolling: true,
        interval: 300,
      },
      warmup: {
        clientFiles: ['src/main.tsx'],
      },
    },
    build: {
      target: 'es2019',
      chunkSizeWarningLimit: 1024,
      minify: 'oxc',
      reportCompressedSize: false,
    },
  };
});
