// <auto-generated />

import type { AuthConfig, LoginMethod } from '@ikonai/sdk-react-ui';

declare const __IKON_AUTH_ENABLED__: boolean | undefined;
declare const __IKON_AUTH_METHODS__: LoginMethod[] | undefined;
declare const __IKON_AUTH_SPACE_ID__: string | undefined;
declare const __IKON_BACKEND_URL__: string | undefined;
declare const __IKON_AUTH_URL__: string | undefined;
declare const __IKON_LOCAL_IKON_SERVER_ENABLED__: boolean | undefined;
declare const __IKON_LOCAL_IKON_SERVER_HOST__: string | undefined;
declare const __IKON_LOCAL_IKON_SERVER_PORT__: number | undefined;

declare global {
  interface Window {
    __IKON_AUTH_CONFIG__?: {
      enabled: boolean;
      methods: LoginMethod[];
      spaceId: string;
      backendUrl?: string;
      authUrl?: string;
    };
    __IKON_LOCAL_IKON_SERVER_CONFIG__?: {
      enabled: boolean;
      host: string;
      port: number;
    };
  }
}

if (typeof __IKON_AUTH_ENABLED__ === 'undefined') {
  throw new Error('__IKON_AUTH_ENABLED__ is not defined');
}
if (typeof __IKON_AUTH_METHODS__ === 'undefined') {
  throw new Error('__IKON_AUTH_METHODS__ is not defined');
}
if (typeof __IKON_AUTH_SPACE_ID__ === 'undefined') {
  throw new Error('__IKON_AUTH_SPACE_ID__ is not defined');
}
if (typeof __IKON_BACKEND_URL__ === 'undefined') {
  throw new Error('__IKON_BACKEND_URL__ is not defined');
}
if (typeof __IKON_AUTH_URL__ === 'undefined') {
  throw new Error('__IKON_AUTH_URL__ is not defined');
}
if (typeof __IKON_LOCAL_IKON_SERVER_ENABLED__ === 'undefined') {
  throw new Error('__IKON_LOCAL_IKON_SERVER_ENABLED__ is not defined');
}
if (typeof __IKON_LOCAL_IKON_SERVER_HOST__ === 'undefined') {
  throw new Error('__IKON_LOCAL_IKON_SERVER_HOST__ is not defined');
}
if (typeof __IKON_LOCAL_IKON_SERVER_PORT__ === 'undefined') {
  throw new Error('__IKON_LOCAL_IKON_SERVER_PORT__ is not defined');
}

window.__IKON_AUTH_CONFIG__ = {
  enabled: __IKON_AUTH_ENABLED__,
  methods: __IKON_AUTH_METHODS__,
  spaceId: __IKON_AUTH_SPACE_ID__,
  backendUrl: __IKON_BACKEND_URL__ || undefined,
  authUrl: __IKON_AUTH_URL__ || undefined,
};

window.__IKON_LOCAL_IKON_SERVER_CONFIG__ = {
  enabled: __IKON_LOCAL_IKON_SERVER_ENABLED__,
  host: __IKON_LOCAL_IKON_SERVER_HOST__,
  port: __IKON_LOCAL_IKON_SERVER_PORT__,
};

export const authConfig = window.__IKON_AUTH_CONFIG__ as AuthConfig;
