// <auto-generated />

import type { AuthConfig, LoginMethod } from '@ikonai/sdk-react-ui';

declare const __IKON_AUTH_ENABLED__: boolean | undefined;
declare const __IKON_AUTH_METHODS__: LoginMethod[] | undefined;
declare const __IKON_AUTH_DEFER_LOGIN__: boolean | undefined;
declare const __IKON_AUTH_SPACE_ID__: string | undefined;
declare const __IKON_BACKEND_URL__: string | undefined;
declare const __IKON_AUTH_URL__: string | undefined;
declare const __IKON_DEV_LOGIN_TOKEN__: string | undefined;
declare const __IKON_DEV_LOGIN_RUN_ID__: string | undefined;
declare const __IKON_LOCAL_IKON_SERVER_ENABLED__: boolean | undefined;
declare const __IKON_LOCAL_IKON_SERVER_HOST__: string | undefined;
declare const __IKON_LOCAL_IKON_SERVER_PORT__: number | undefined;
declare const __IKON_BOOT_SNAPSHOT_FILE__: string | undefined;

declare global {
  interface Window {
    __IKON_AUTH_CONFIG__?: {
      enabled: boolean;
      methods: LoginMethod[];
      spaceId: string;
      deferLogin?: boolean;
      backendUrl?: string;
      authUrl?: string;
      devLoginToken?: string;
      devLoginRunId?: string;
    };
    __IKON_LOCAL_IKON_SERVER_CONFIG__?: {
      enabled: boolean;
      host: string;
      port: number;
    };
    __IKON_BOOT_SNAPSHOT_FILE__?: string;
    __IKON_BOOT_SNAPSHOT_ROUTE__?: string;
  }
}

if (typeof __IKON_AUTH_ENABLED__ === 'undefined') {
  throw new Error('__IKON_AUTH_ENABLED__ is not defined');
}
if (typeof __IKON_AUTH_METHODS__ === 'undefined') {
  throw new Error('__IKON_AUTH_METHODS__ is not defined');
}
if (typeof __IKON_AUTH_SPACE_ID__ === 'undefined') {
  throw new Error('__IKON_AUTH_SPACE_ID__ is not defined');
}
if (typeof __IKON_BACKEND_URL__ === 'undefined') {
  throw new Error('__IKON_BACKEND_URL__ is not defined');
}
if (typeof __IKON_AUTH_URL__ === 'undefined') {
  throw new Error('__IKON_AUTH_URL__ is not defined');
}
if (typeof __IKON_LOCAL_IKON_SERVER_ENABLED__ === 'undefined') {
  throw new Error('__IKON_LOCAL_IKON_SERVER_ENABLED__ is not defined');
}
if (typeof __IKON_LOCAL_IKON_SERVER_HOST__ === 'undefined') {
  throw new Error('__IKON_LOCAL_IKON_SERVER_HOST__ is not defined');
}
if (typeof __IKON_LOCAL_IKON_SERVER_PORT__ === 'undefined') {
  throw new Error('__IKON_LOCAL_IKON_SERVER_PORT__ is not defined');
}

window.__IKON_AUTH_CONFIG__ = {
  enabled: __IKON_AUTH_ENABLED__,
  methods: __IKON_AUTH_METHODS__,
  spaceId: __IKON_AUTH_SPACE_ID__,
  // Optional define (older scaffolds don't emit it) — absence means no deferred login.
  deferLogin: (typeof __IKON_AUTH_DEFER_LOGIN__ !== 'undefined' && __IKON_AUTH_DEFER_LOGIN__) || undefined,
  backendUrl: __IKON_BACKEND_URL__ || undefined,
  authUrl: __IKON_AUTH_URL__ || undefined,
  devLoginToken: (typeof __IKON_DEV_LOGIN_TOKEN__ !== 'undefined' && __IKON_DEV_LOGIN_TOKEN__) || undefined,
  devLoginRunId: (typeof __IKON_DEV_LOGIN_RUN_ID__ !== 'undefined' && __IKON_DEV_LOGIN_RUN_ID__) || undefined,
};

window.__IKON_LOCAL_IKON_SERVER_CONFIG__ = {
  enabled: __IKON_LOCAL_IKON_SERVER_ENABLED__,
  host: __IKON_LOCAL_IKON_SERVER_HOST__,
  port: __IKON_LOCAL_IKON_SERVER_PORT__,
};

// ||= so a prerendered page's inline script (which pins the exact per-route snapshot file before
// any module script runs) wins over the build-time define, which only knows the root snapshot.
window.__IKON_BOOT_SNAPSHOT_FILE__ ||= __IKON_BOOT_SNAPSHOT_FILE__ || '';

export const authConfig = window.__IKON_AUTH_CONFIG__ as AuthConfig;
