# Database configurations for allocating databases for the app (run 'ikon app config' to apply changes)
# Assigned database connection info is available via app.Databases in the app. Use 'ikon app db' commands to manage databases.
# Format: "name:type" - valid types: postgres
# Examples: "mydb:postgres"
Databases = []

# Endpoint configurations for exposing the app externally (assigned port numbers and public URLs are available via app.Endpoints in the app)
# Format: "name:protocol" - valid protocols: http, https, tls, tcp
# Examples: "api:https", "webhooks:http", "gameserver:tcp"
Endpoints = []

# Activation configuration for the app (app activation is separate from deployment)
[Activation]
# Whether to stop all active sessions of the app when a version of the app is activated
StopSessions = false

# Authentication configuration for the app frontend
[Auth]
# Whether the frontend requires authentication before connection to the app is established
Enabled = false
# Available methods: google, microsoft, guest
Methods = ["google"]
# If non-empty, only allow users with email addresses from these domains to authenticate (e.g. ["mycompany.com"])
DomainAllowlist = []

# Target information for deployment (automatically configured with 'ikon app config')
[Target]
OrganisationId = ""
SpaceId = ""
ChannelId = ""
Name = ""
