// <auto-generated />
import react from '@vitejs/plugin-react';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';
import { defineConfig, loadEnv } from 'vite';

const __dirname = import.meta.dirname;

function resolvePackageExport(specifier) {
  try {
    return fileURLToPath(import.meta.resolve(specifier));
  } catch {
    return undefined;
  }
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), 'VITE_');
  const isIkonInternal = (process.env.VITE_IS_IKON_INTERNAL || env.VITE_IS_IKON_INTERNAL) === 'true';
  const platformTypescriptPath = process.env.VITE_IKON_PLATFORM_TYPESCRIPT_PATH || env.VITE_IKON_PLATFORM_TYPESCRIPT_PATH;
  const sourceMode = isIkonInternal && platformTypescriptPath;

  const standardPrerenderDir = sourceMode
    ? resolve(platformTypescriptPath, 'sdk/sdk-react-ui-standard/src/prerender')
    : undefined;

  const entry = sourceMode
    ? resolve(standardPrerenderDir, 'prerender-entry.tsx')
    : resolvePackageExport('@ikonai/sdk-react-ui-standard/prerender-entry');

  if (!entry) {
    throw new Error('The installed @ikonai/sdk-react-ui-standard has no prerender entry; run `ikon app update` to update the SDK packages');
  }

  const workerStub = sourceMode
    ? resolve(standardPrerenderDir, 'prerender-worker-stub.ts')
    : resolvePackageExport('@ikonai/sdk-react-ui-standard/prerender-worker-stub');

  const appPrerenderModules = resolve(__dirname, 'src/prerender-modules.ts');
  const defaultPrerenderModules = sourceMode
    ? resolve(standardPrerenderDir, 'prerender-modules-default.ts')
    : resolvePackageExport('@ikonai/sdk-react-ui-standard/prerender-modules-default');
  const prerenderModules = existsSync(appPrerenderModules) ? appPrerenderModules : defaultPrerenderModules;

  const alias = [];

  if (workerStub) {
    alias.push({ find: /^.*\?worker$/, replacement: workerStub });
  }

  if (prerenderModules) {
    alias.push({ find: 'virtual:ikon-prerender-modules', replacement: prerenderModules });
  }

  if (sourceMode) {
    for (const [name, path] of [
      ['@ikonai/sdk', 'sdk/sdk/src/index.ts'],
      ['@ikonai/sdk-libopus', 'sdk/sdk-libopus/src/index.ts'],
      ['@ikonai/sdk-react-ui', 'sdk/sdk-react-ui/src/index.ts'],
      ['@ikonai/sdk-react-ui-standard', 'sdk/sdk-react-ui-standard/src/index.ts'],
      ['@ikonai/sdk-react-ui-rive', 'sdk/sdk-react-ui-rive/src/index.ts'],
      ['@ikonai/sdk-ui', 'sdk/sdk-ui/src/index.ts'],
      ['@ikonai/configs', 'shared/configs/src/index.ts'],
      ['@ikonai/protocol', 'shared/protocol/src/index.ts'],
    ]) {
      alias.push({ find: name, replacement: resolve(platformTypescriptPath, path) });
    }
  }

  return {
    plugins: [react()],
    resolve: {
      alias,
      dedupe: ['react', 'react-dom'],
    },
    build: {
      ssr: entry,
      outDir: resolve(__dirname, 'build/prerender'),
      emptyOutDir: true,
      target: 'node20',
      rollupOptions: {
        output: {
          format: 'es',
          entryFileNames: 'entry-prerender.mjs',
          chunkFileNames: 'assets/[name]-[hash].mjs',
        },
      },
    },
    ssr: {
      noExternal: true,
    },
  };
});
